on: [deployment_status]

jobs:
  notification:
    runs-on: ubuntu-latest
    steps: 
      - name: Telegram Deployment Notification
        uses: appleboy/telegram-action@master
        if: github.event.deployment_status.state != 'pending'
        with:
          token: ${{ secrets.TELEGRAM_API_KEY }}
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          args: |
            ${{ github.repository }}: ${{ github.event.deployment_status.description }} ${{ github.event.deployment_status.target_url }}
          
